# Generated by Django 5.0.6 on 2024-09-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(db_column='id_odont', on_delete=django.db.models.deletion.CASCADE, to='server.odontologo')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Miércoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(db_column='id_odont', on_delete=django.db.models.deletion.CASCADE, to='server.odontologo')),
            ],
        ),
    ]
