# Generated by Django 5.0.6 on 2024-09-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_agendadoctor_horariorecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_serv',
            field=models.ForeignKey(db_column='id_serv', default=1, on_delete=django.db.models.deletion.CASCADE, to='server.servicioodontologico'),
            preserve_default=False,
        ),
    ]
