# Generated by Django 5.0.6 on 2024-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_cita_id_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendadoctor',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
