# Generated by Django 5.0.6 on 2024-09-19 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_agendadoctor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciohistoria',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciohistoria',
            name='id_serv',
            field=models.OneToOneField(db_column='id_serv', on_delete=django.db.models.deletion.CASCADE, to='server.servicioodontologico'),
        ),
    ]
