# Generated by Django 5.0.6 on 2024-09-19 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_serviciohistoria_id_alter_serviciohistoria_id_serv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohistoria',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviciohistoria',
            name='id_serv',
            field=models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.CASCADE, to='server.servicioodontologico'),
        ),
    ]
